<?php

namespace JohnLobo\CustomValidator;

use Illuminate\Contracts\Translation\Translator;
use Illuminate\Validation\Validator;

class CustomValidator extends Validator
{
    public  $custom_messages=[
       'specific_validation'=>'The :attribute must john did',

    ];
    private $_custom_messages = array(
        "today_onwards" => "The :attribute must be today onwards qrwq",
        'john_validation'=>'The :attribute must be today onwards',
    );
    public function __construct(Translator $translator, array $data, array $rules, array $messages = [], array $customAttributes = [])
    {
        parent::__construct($translator, $data, $rules, $messages, $customAttributes);
        $this->setCustomMessages( $this->custom_messages );
        $this->_set_custom_stuff();
    }


    protected function validateSpecificValidation($attribute, $value)
    {

        if($value=='John'){
            return true;
        } else{
            return false;
        }
    }
    protected function validateJohnValidation($attribute, $value)
    {

        if($value=='John'){
            return true;
        } else{
            return false;
        }
    }


    protected function _set_custom_stuff() {
        //setup our custom error messages
     //   $this->setCustomMessages($this->customMessages);
        $this->setCustomMessages( $this->_custom_messages );
    }

    protected function validateTodayOnwards( $attribute, $value ) {
        $now =  strtotime('-1 day');
        $valueDateFormat =  strtotime($value);

        if($valueDateFormat > $now){
            return true;
        }
        else {
            return false;

        }
    }

    public function fails()
    {
        return parent::fails(); // TODO: Change the autogenerated stub
    }


    /*
     * http://www.expertphp.in/article/how-to-create-custom-validation-rules-with-laravel-5
https://medium.com/@juampi92/laravel-5-5-validation-ruleception-rule-inside-rule-2762d2cf4471
https://appdividend.com/2017/09/02/laravel-5-5-validation-example-scratch/
https://laracasts.com/discuss/channels/laravel/laravel-55-can-i-pass-value-to-custom-rule?page=0
https://marabesi.com/php/2017/05/31/laravel-custom-validator.html
https://stackoverflow.com/questions/30025252/laravel-extended-validation-custom-message
https://laraveldaily.com/how-to-create-custom-validation-rules-laravel/
https://stackoverflow.com/questions/28417977/custom-validator-in-laravel-5
https://divinglaravel.com/package-auto-discovery/discovering-packages
    https://stackoverflow.com/questions/33134878/custom-validation-replacers-in-laravel-5-1
    http://kaltencoder.com/2015/07/laravel-5-package-creation-tutorial-part-2/
     */


}